version: '3'

services:
  web:
    build:
      context: .
      dockerfile: .docker/node.dockerfile
      target: dev
    ports:
      - '5173:5173'
      - '4173:4173'
    volumes:
      - .:/app
      - /app/node_modules
    container_name: front-nexus
